import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { LotCard } from "@/components/lot-card";
import { lots, type Lot, type LotStatus } from "@/lib/lots";
import { waLink, waLotMessage } from "@/lib/whatsapp";
import { Button } from "@/components/ui/button";
import { X } from "lucide-react";

export const Route = createFileRoute("/catalogo")({ head: () => ({ meta: [{ title: "Catálogo de Gado | Noro" },{ name:"description",content:"Consulte lotes de gado disponíveis, reservados e vendidos pela Noro no Paraná."},{property:"og:title",content:"Catálogo de Gado | Noro"},{property:"og:description",content:"Lotes com informação objetiva e negociação acompanhada."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }), component: Catalogo });

function Catalogo() {
  const [status,setStatus]=useState<"Todos"|LotStatus>("Todos"); const [selected,setSelected]=useState<Lot>();
  const filtered=useMemo(()=>status==="Todos"?lots:lots.filter(l=>l.status===status),[status]);
  const reais=filtered.filter(l=>l.real); const demos=filtered.filter(l=>!l.real);
  return <main className="min-h-screen px-5 pb-24 pt-36 md:px-10"><div className="mx-auto max-w-[1440px]">
    <p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Catálogo Noro</p><div className="mt-5 grid gap-6 border-b border-border pb-10 lg:grid-cols-[1.2fr_.8fr]"><h1 className="font-display text-6xl leading-none md:text-8xl">Oportunidades em gado.</h1><p className="max-w-lg self-end text-base leading-7 text-muted-foreground">Confira informações essenciais antes do contato. O lote NR-101 já está em campo — os demais servem de modelo até os próximos lotes entrarem.</p></div>
    <div className="mt-8 flex flex-wrap gap-2" aria-label="Filtrar por status">{(["Todos","Disponível","Reservado","Vendido"] as const).map(s=><Button key={s} variant={status===s?"default":"outline"} onClick={()=>setStatus(s)}>{s}</Button>)}</div>
    {reais.length>0 && <section className="mt-14"><div className="flex flex-wrap items-center gap-3 border-b border-border pb-4"><span className="bg-primary px-3 py-1.5 text-[0.65rem] font-bold uppercase tracking-[0.14em] text-hero-foreground">Lotes reais</span><h2 className="font-display text-3xl">Animais em campo agora</h2></div><div className="mt-8 grid gap-12 md:grid-cols-2 lg:grid-cols-3">{reais.map(l=><LotCard key={l.id} lot={l} onOpen={setSelected}/>)}</div></section>}
    {demos.length>0 && <section className="mt-16"><div className="flex flex-wrap items-center gap-3 border-b border-border pb-4"><span className="border border-border px-3 py-1.5 text-[0.65rem] font-bold uppercase tracking-[0.14em] text-muted-foreground">Exemplos</span><h2 className="font-display text-3xl text-muted-foreground">Modelo de apresentação dos lotes</h2></div><div className="mt-8 grid gap-12 md:grid-cols-2 lg:grid-cols-3">{demos.map(l=><LotCard key={l.id} lot={l} onOpen={setSelected}/>)}</div></section>}
  </div>
  {selected && <div className="fixed inset-0 z-[60] flex items-end bg-hero/70 p-0 backdrop-blur-sm md:items-center md:justify-center md:p-8" role="dialog" aria-modal="true" aria-label={`Detalhes do lote ${selected.id}`}><div className="max-h-[92svh] w-full overflow-y-auto bg-background md:max-w-4xl"><div className="flex justify-end p-3"><Button size="icon" variant="ghost" onClick={()=>setSelected(undefined)} aria-label="Fechar"><X/></Button></div><div className="grid md:grid-cols-2"><div className="bg-muted">{selected.videoUrl && <video src={selected.videoUrl} controls playsInline className="aspect-video w-full object-cover"/>}{selected.images.map(src=><img key={src} src={src} alt={selected.title} width={1408} height={1056} className="w-full object-cover"/>)}</div><div className="p-7 md:p-10"><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Lote {selected.id} · {selected.status}</p><h2 className="mt-3 font-display text-5xl">{selected.title}</h2><dl className="mt-8 grid grid-cols-2 gap-y-5 border-y border-border py-6 text-sm">{[["Raça",selected.breed],["Categoria",selected.category],["Quantidade",selected.quantity],["Sexo",selected.sex],["Idade",selected.age],["Peso",selected.arrobas==="A confirmar"?selected.weight:`${selected.weight} / ${selected.arrobas}`],["Local",selected.location],["Frete",selected.freight]].map(([k,v])=><div key={k}><dt className="text-xs uppercase text-muted-foreground">{k}</dt><dd className="mt-1 font-semibold">{v}</dd></div>)}</dl><p className="mt-6 text-sm text-muted-foreground">{selected.note}</p><Button asChild size="xl" className="mt-8 w-full"><a href={waLink(waLotMessage(selected.id, selected.title))} target="_blank" rel="noreferrer">Consultar pelo WhatsApp</a></Button></div></div></div></div>}
  </main>;
}